apiVersion: v1
kind: ServiceAccount
metadata:
  name: kube-schedule-scaler
  namespace: kube-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kube-schedule-scaler
rules:
- apiGroups:
  - ""
  resources:
  - namespaces
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - apps
  resources:
  - deployments
  verbs:
  - get
  - list
  - patch
  - update
- apiGroups:
  - autoscaling
  resources:
  - horizontalpodautoscalers
  verbs:
  - get
  - list
  - patch
  - update
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: kube-schedule-scaler
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
- kind: ServiceAccount
  name: kube-schedule-scaler
  namespace: kube-system
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kube-schedule-scaler
  namespace: kube-system
spec:
  replicas: 1
  selector:
    matchLabels:
      application: kube-schedule-scaler
  template:
    metadata:
      labels:
        application: kube-schedule-scaler
    spec:
      serviceAccountName: kube-schedule-scaler
      priorityClassName: system-cluster-critical
      containers:
      - name: kube-schedule-scaler
        image: cwsakamoto/kube-schedule-scaler:latest
        imagePullPolicy: Always
        resources:
          limits:
            cpu: 500m
            memory: 500Mi
          requests:
            cpu: 250m
            memory: 500Mi
