apiVersion: v1
kind: ServiceAccount
metadata:
  name: operator
  namespace: default

apiVersion: apps/v1beta1
kind: Deployment
metadata:
  labels:
    application: kube-schedule-scaler
    version: v0.1
  name: kube-schedule-scaler
spec:
  replicas: 1
  selector:
    matchLabels:
      application: kube-schedule-scaler
  template:
    metadata:
      labels:
        application: kube-schedule-scaler
        version: v0.1
      annotations:
        iam.amazonaws.com/role: "s3-scaling-definitions"
    spec:
      serviceAccountName: operator
      containers:
      - name: kube-schedule-scaler
        image: "{{{IMAGE}}}"
        resources:
          limits:
            cpu: 1000m
            memory: 500Mi
          requests:
            cpu: 500m
            memory: 500Mi 
